/*************************************************************************
* ADOBE CONFIDENTIAL
* ___________________
*
*  Copyright 2015 Adobe Systems Incorporated
*  All Rights Reserved.
*
* NOTICE:  All information contained herein is, and remains
* the property of Adobe Systems Incorporated and its suppliers,
* if any.  The intellectual and technical concepts contained
* herein are proprietary to Adobe Systems Incorporated and its
* suppliers and are protected by all applicable intellectual property laws,
* including trade secret and or copyright laws.
* Dissemination of this information or reproduction of this material
* is strictly forbidden unless prior written permission is obtained
* from Adobe Systems Incorporated.
**************************************************************************/
let initialQuestion;class ActionableCoachmark{constructor(){if(ActionableCoachmark.instance)return ActionableCoachmark.instance;ActionableCoachmark.instance=this,this.shadowRoot=null}id="GenAIWebpageFte";sendAnalyticsEvent=e=>{try{chrome.runtime.sendMessage({main_op:"analytics",analytics:e})}catch(e){}};async clickHandler(e){this.remove(),await initDcLocalStorage();const t=window.dcLocalStorage.getItem("genAiWebpageCoachmarkData")||{};window.dcLocalStorage.setItem("genAiWebpageCoachmarkData",{...t,hasUsedActionableCoachMark:!0}),chrome.runtime.sendMessage({type:"open_side_panel",touchpoint:"actionableCoachmark",initialQuestion:e}),this.sendAnalyticsEvent([["DCBrowserExt:SidePanel:ActionableCoachmark:Clicked"]]),initialQuestion=e}isRendered(){return Boolean(this.shadowRoot)}remove(){this.shadowRoot?.host?.remove(),this.shadowRoot=null,this.sendAnalyticsEvent([["DCBrowserExt:SidePanel:ActionableCoachmark:Removed"]]);(new FABManager).renderFAB()}now=()=>(new Date).getTime();render(){const e=new FABManager;if(e.isFABRendered()&&e.removeFAB(),this.isRendered())return;const t=document.createElement("div");t.id="aiAcShadowRoot",t.style.display="block",this.shadowRoot=t.attachShadow({mode:"open"}),fetch(chrome.runtime.getURL("resources/SidePanel/ActionableCoachmark.html")).then((e=>e.text())).then((e=>{const a=document.createElement("template");a.innerHTML=e;const o=a.content;this.shadowRoot.appendChild(o.cloneNode(!0)),this.shadowRoot.querySelector(".close-btn").addEventListener("click",(()=>{this.remove()}));const n=this.shadowRoot.querySelector(".nudgeInput");AnimateCannedQuestions.start(n),n.addEventListener("keydown",(e=>{"Enter"===e.key&&this.clickHandler(AnimateCannedQuestions.getQuestion())}));this.shadowRoot.querySelector(".submitBtn").addEventListener("click",(async()=>{this.clickHandler(AnimateCannedQuestions.getQuestion())})),util.translateElements(".translate",this.shadowRoot),document.body.appendChild(t),this.updateShowCount(),this.sendAnalyticsEvent([["DCBrowserExt:SidePanel:ActionableCoachmark:Displayed"]])}))}async isEligible(){return!!await GenAIWebpageEligibilityService.shouldShowTouchpoints()&&(!await GenAIWebpageEligibilityService.shouldDisableTouchpoints()&&this.shouldShow())}async shouldShow(){await initDcLocalStorage();const{hasUsedActionableCoachMark:e,lastShownTimestamp:t,showCount:a=0}=window.dcLocalStorage.getItem("genAiWebpageCoachmarkData")||{};return!e&&(!t||a<3&&this.now()-t>=864e6)}updateShowCount=async()=>{await initDcLocalStorage();const{showCount:e=0}=window.dcLocalStorage.getItem("genAiWebpageCoachmarkData")||{};window.dcLocalStorage.setItem("genAiWebpageCoachmarkData",{lastShownTimestamp:this.now(),showCount:e+1})}}